[2024-04-26 11:49:12,631] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:12] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:16,315] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:16] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:16,434] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:16] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:20,677] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:20] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:20,754] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:20] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:28,850] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:28] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:28,864] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:28] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:30,553] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:30] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:30,572] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:30] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:32,849] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:32] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:32,996] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:32] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:36,635] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:36] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:49:36,638] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:49:36] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:50:29,884] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:50:29] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:50:29,973] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:50:29] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:50:32,140] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:50:32] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:51:02,219] ERROR log_exception() L838  Exception on /hikes [GET] - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/flask/app.py L838 
Traceback (most recent call last):
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/flask/app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/flask/app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/flask/app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/flask/app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/flask_openapi3/scaffold.py", line 117, in view_func
    response = func(**func_kwargs)
               ^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/app.py", line 134, in get_hikes
    hikes = session.query(Hike).all()
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/orm/query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2181, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 2050, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1144, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3280, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 3304, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/sqlalchemy/pool/impl.py", line 168, in _do_get
    raise exc.TimeoutError(
sqlalchemy.exc.TimeoutError: QueuePool limit of size 5 overflow 10 reached, connection timed out, timeout 30.00 (Background on this error at: https://sqlalche.me/e/20/3o7r)
[2024-04-26 11:51:02,285] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:51:02] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:51:02,288] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:51:02] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:51:02,292] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:51:02] "GET /hikes HTTP/1.1" 200 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:51:02,362] INFO _log() L96   127.0.0.1 - - [26/Apr/2024 11:51:02] "[35m[1mGET /hikes HTTP/1.1[0m" 500 - - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/env/lib/python3.11/site-packages/werkzeug/_internal.py L96  
[2024-04-26 11:51:46,071] WARNING add_user() L225  Erro ao adicionar usu√°rio'Yuri', Usu√°rio de mesmo nome j√° salvo na base :/ - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/app.py L225 
[2024-04-26 11:51:46,090] WARNING add_user() L225  Erro ao adicionar usu√°rio'Yuri', Usu√°rio de mesmo nome j√° salvo na base :/ - call_trace=/Users/yuricooke/Documents/GIT/FS_BE_API/app.py L225 
